services:
  - type: web
    name: demano-bank-api
    runtime: python
    buildCommand: bash build.sh
    startCommand: gunicorn banque_api.wsgi:application
    plan: free
    autoDeploy: true
    envVars:
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com,demano-bank-api.vercel.app,localhost,127.0.0.1"
      - key: SECRET_KEY
        generateValue: true
