# Generated by Django 4.2.30 on 2026-04-19 13:45

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompteBancaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_compte', models.CharField(help_text='Numéro unique du compte bancaire', max_length=20, unique=True)),
                ('nom_titulaire', models.CharField(help_text='Nom complet du titulaire du compte', max_length=100)),
                ('type_compte', models.CharField(choices=[('COURANT', 'Compte Courant'), ('EPARGNE', 'Compte Épargne'), ('TERME', 'Compte à Terme')], default='COURANT', help_text='Type de compte bancaire', max_length=10)),
                ('solde', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Solde actuel du compte en unité monétaire', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('date_ouverture', models.DateTimeField(auto_now_add=True, help_text="Date et heure d'ouverture du compte")),
                ('date_modification', models.DateTimeField(auto_now=True, help_text='Dernière date de modification du compte')),
                ('actif', models.BooleanField(default=True, help_text="Statut d'activation du compte")),
            ],
            options={
                'verbose_name': 'Compte Bancaire',
                'verbose_name_plural': 'Comptes Bancaires',
                'ordering': ['-date_ouverture'],
            },
        ),
    ]
