# Generated by Django 4.2.30 on 2026-04-23 04:29

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionBancaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_transaction', models.CharField(choices=[('DEPOT', 'Dépôt'), ('RETRAIT', 'Retrait')], help_text='Type de transaction bancaire', max_length=10)),
                ('montant', models.DecimalField(decimal_places=2, help_text='Montant positif de la transaction', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))])),
                ('solde_avant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('solde_apres', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('date_transaction', models.DateTimeField(auto_now_add=True)),
                ('compte', models.ForeignKey(help_text='Compte concerné par la transaction', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='comptes.comptebancaire')),
            ],
            options={
                'verbose_name': 'Transaction Bancaire',
                'verbose_name_plural': 'Transactions Bancaires',
                'ordering': ['-date_transaction'],
            },
        ),
    ]
